// Copyright © 2018-2019 Apollo Technologies Pte. Ltd. All Rights Reserved.

package tx

import (
	"github.com/HiNounou029/nounouchain/polo"
)

// Event represents a contract event log. These events are generated by the LOG opcode and
// stored/indexed by the node.
type Event struct {
	// address of the contract that generated the event
	Address polo.Address
	// list of topics provided by the contract.
	Topics []polo.Bytes32
	// supplied by the contract, usually ABI-encoded
	Data []byte
}

// Events slice of event logs.
type Events []*Event
